#!/bin/bash
docker run \
    --rm \
    --name artifactory \
    -d \
    -v /etc/localtime:/etc/localtime \
    -v /artifactory/db:/artifactory/db \
    -v /artifactory/data:/artifactory/data \
    -v /artifactory/access/etc:/artifactory/access/etc \
    -v /artifactory/access/data:/artifactory/access/data \
    -v /var/log/artifactory:/artifactory/logs \
    -v /var/backups/artifactory:/artifactory/backups \
    -e DB_ROOT_PASSWORD="some_password" \
    -e DB_USER_PASSWORD="some_password" \
    -p 8006:8006 \
        artifactory
