#!/bin/bash

stopDbCmd="mysqladmin --user=root --password="$DB_ROOT_PASSWORD" shutdown"
stopWebCmd="/artifactory/scripts/webShutdown"
stopDummyCmd="ps axf | grep containerDummy | grep -v grep | awk '{print "kill -9 " $1}' | sh"

$stopWebCmd && $stopDbCmd && $stopDummyCmd
