#!/bin/bash
if [ ! -d /artifactory/db/mysql ];
then
    mysql_install_db
fi

sed -i 's|\(\s*\)#password: .*|\1password: "'"$DB_USER_PASSWORD"'"|' $ARTIFACTORY_HOME/var/etc/system.yaml

trap /artifactory/scripts/containerShutdown SIGHUP SIGINT SIGTERM TERM

mysqld &
/artifactory/scripts/webStartup &
/artifactory/scripts/containerDummy
