#!/bin/bash
if [ ! -d /artifactory/db/mysql ];
then
    mysql_install_db
fi

trap /artifactory/scripts/shutdown SIGHUP SIGINT SIGTERM TERM

mysqld & /usr/share/tomcat8/bin/startup.sh & apache2ctl -D FOREGROUND & wait
