#!/bin/bash
if [ ! -d /artifactory/db/mysql ];
then
    mysql_install_db
fi

sed -i 's|password.*|password='"$DB_USER_PASSWORD"'|' $ARTIFACTORY_HOME/etc/db.properties

trap /artifactory/scripts/shutdown SIGHUP SIGINT SIGTERM TERM

startMySQLCmd="mysqld"
startTomcatCmd="$CATALINA_HOME/bin/catalina.sh run"
$startMySQLCmd & $startTomcatCmd & wait
