#!/bin/bash
if [ "$1" != "" ];
then
    DUMP="$DB_NAME.dump"
    DUMPFILE="/artifactory/$DUMP"
    FILE="/artifactory/backups/$1.tar.gz"
    startWebCmd="/artifactory/scripts/webStartup"
    stopWebCmd="/artifactory/scripts/webShutdown"

    if [ -e "$FILE" ];
    then
        $stopWebCmd

        cd /artifactory
        tar -xzf $FILE $DUMP data security

        mysql --user="$DB_USER_NAME" --password="$DB_USER_PASSWORD" "$DB_NAME" < $DUMPFILE

        rm $DUMPFILE

        $startWebCmd &
    fi
fi
